# Generated by Django 4.2.6 on 2023-10-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
